#include "templates.h"
#include "color_codes.h"


const char* build_template_library =
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include <string.h>\n"
    "#include \"../src_files.h\"\n"
    "#include \"color_codes.h\"\n"
    "\n"
    "int main() {\n"
    "    char obj_cmd[512];\n"
    "    char base[64];\n"
    "\n"
    "    for (int i = 0; files[i] != NULL; i++) {\n"
    "        const char* path = files[i];\n"
    "        const char* slash = strrchr(path, '/');\n"
    "        if (!slash) continue;\n"
    "        slash++;\n"
    "\n"
    "        const char* dot = strrchr(slash, '.');\n"
    "        if (!dot) continue;\n"
    "        int len = dot - slash;\n"
    "        strncpy(base, slash, len);\n"
    "        base[len] = '\\0';\n"
    "\n"
    "        snprintf(obj_cmd, sizeof(obj_cmd),\n"
    "            \"gcc -c -Iinclude %s -o build/%s.o\",\n"
    "            path, base);\n"
    "\n"
    "        printf(\"[nexus] Compiling: %s\\n\", obj_cmd);\n"
    "        if (system(obj_cmd) != 0) {\n"
    "            fprintf(stderr, \"[nexus] Compilation failed: %s\\n\", path);\n"
    "            return 1;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    printf(\"[nexus] Archiving static library: lib/libmylib.a\\n\");\n"
    "    int res = system(\"ar rcs lib/libmylib.a build/*.o\");\n"
    "    if (res != 0) {\n"
    "        fprintf(stderr, \"[nexus] Archiving failed.\\n\");\n"
    "        return 1;\n"
    "    }\n"
    "\n"
    "    printf(GREEN \"[nexus]\\033[0m Library built successfully.\\n\");\n"
    "    return 0;\n"
    "}\n";

const char* build_template_executable = 
    "#include <stdio.h>\n"
    "#include <stdlib.h>\n"
    "#include \"color_codes.h\"\n"
    "#include \"../src_files.h\"\n"
    "#include <string.h>\n\n"
    "/*\n"
    "    Use gcc for C files or g++ for c++\n"
    "    Performs compilation and linking with -o all at once\n"
    "*/\n"
    "\n"
    "int main() {\n"
    "   char comp[] = \"gcc -o \";\n"
    "\n"
    "   /*\n"
    "       Provide directory and output exe name here.\n"
    "       Provide relative path from the \"build\" directory\n"
    "   */\n"
    "   char out_name[] = \"bin/main\";    // change \"bin\" and \"main\" if you wish\n"
    "\n"
    "   /*\n"
    "       Command input buffer is 2048 chars.\n"
    "       If you have a lot of files, just input whatever you need for a size. (FIX)\n"
    "   */\n"
    "   char cmd[2048] = {0};\n"
    "\n"
    "   strcat(cmd, comp);\n"
    "   strcat(cmd, out_name);\n"
    "\n"
    "   int i = 0;\n"
    "   while (files[i] != NULL) {\n"
    "       strcat(cmd, \" \");\n"
    "       strcat(cmd, files[i]);\n"
    "       i++;\n"
    "   }\n"
    "\n"
    "   printf(\"Compiling and linking: %s\\n\", cmd);\n"
    "   int result = system(cmd);\n"
    "\n"
    "   if (result != 0) {\n"
    "       fprintf(stderr, \"Compilation or linking failed with code %d\\n\", result);\n"
    "       return 1;\n"
    "   }\n"
    "\n"
    "   printf(GREEN \"Compilation and linking successful.\\033[0m\\n\");\n"
    "\n"
    "   return 0;\n"
    "}\n";



const char* main_template = 
    "#include <stdio.h>\n\n"
    "int main() {\n"
    "   printf(\"Hello, World!\\n\");\n"
    "   return 0;\n"
    "}\n";

const char* lib_template = 
    "/*\n"
    "   Add library code in this file.\n"
    "   Add headers for associated .c files in include/\n"
    "*/\n";

const char* color_codes_template =
    "#ifndef COLOR_CODES_H\n"
    "#define COLOR_CODES_H\n"
    "\n"
    "#define GREEN \"\\033[0;32m\"\n"
    "#define RED \"\\033[0;31m\"\n"
    "#define YELLOW \"\\033[0;33m\"\n"
    "#define RESET \"\\033[0m\"\n"
    "\n"
    "#endif\n";